### ISSUE TITLE
Meetup #4 Notes collection

### ISSUE THREAD

**Issue by asaaki** [micromodules/meetup#4]
Post your comment with finding and links here. :memo: 

_(At one point we will compile this down for the `NOTES.md` file.)_

**Comment by asaaki** [comment]
First, the pretty nice ISO standard when it comes to dates, times, periods and their representation:
https://en.wikipedia.org/wiki/ISO_8601
(at least the way to go for unambiguous display of such things)

Blog by Lau ([@lau](https://github.com/lau)): http://www.creativedeletion.com/
He thinks and writes a lot about date/time handling. I guess it is his obsession. :smile: 

Most recent article:
http://www.creativedeletion.com/2016/02/04/timetypes_prevent_bugs.html
The tl;dr is that we probably need more specific types to represent the date and time data we (or the users) actually mean.
Something which is mostly forgotten is the _local time_ (time without timezone data), where a person refers to a time based on their or another location, which maybe isn't always clear/absolute in the beginning. Think of cases like alarms on your mobile phone, which is then even location-unaware, because you want the phone ring at 08:00 in the morning, no matter where on planet earth you currently are.

http://www.creativedeletion.com/2015/12/03/timezone-updates-need-fixing.html
This article shows the problem we have when it comes to timezones. The database changes more often than you think and probably the timezone data your application/system uses is already outdated.

And btw do not run your server in anything else than UTC:
http://www.creativedeletion.com/2015/08/07/why-not-to-use-server-local-time.html
(Believe it or not, but I already worked for a company where the server ran in CE(S)T, and the DST is your enemy here! Twice a year!)

Here is his library you want to use when you have to deal with dates and times in **Elixir**:
https://github.com/lau/calendar
as well as
https://github.com/lau/tzdata (extracted from the calendar library)

**Comment by asaaki** [comment]
List of all past leap seconds so far: https://www.ietf.org/timezones/data/leap-seconds.list

**Comment by asaaki** [comment]
Ruby library for durations: https://github.com/peleteiro/ruby-duration

And this is how Rails does it:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/duration.rb
(also look for all date and time related files in ActiveSupport)

**Comment by asaaki** [comment]
And the ISO8601 library for Ruby: https://github.com/arnau/ISO8601

**Comment by asaaki** [comment]
Ruby's Time class doesn't break here, but returns a wrong result:

``` ruby
Time.utc(2015,6,30,23,59,60) # 2015-06-30T23:59:60 - the recent leap second date
#=> 2015-07-01 00:00:00 UTC
```

So, do not rely on the standard library for everything time related, because all times with `60` in the seconds part are valid and do not raise an error.

**Comment by jdinartejesus** [comment]
Here is library for IOS for manage time.
https://github.com/naoty/Timepiece

```
let now = NSDate()
let nextWeek = now + 1.week
```

**Comment by agermanidis** [comment]
Github hover extension: https://chrome.google.com/webstore/detail/github-hovercard/mmoahbbnojgkclgceahhakhnccimnplk

clj-time library: https://github.com/clj-time/clj-time
